name: 'JSDoc Action'
description: 'GitHub Action to build JSDoc documentation'
author: 'Anastasiya Trembach'
branding:
  icon: 'file-text'  
  color: 'yellow'
inputs:
  source_dir: './'
  output_dir: './docs'
  front_page: './README.md'
runs:
  using: 'node12'
  main: 'Table.js'